### PR TITLE
Support Laravel 9

### PR DESCRIPTION
**Pull request by Yanohd**
With this pull request, we satisfy Laravel 9 requirements.
#15

### CODE REVIEW

**Comment by FarukErtuerk** [comment]
Can you run the tests in the pipeline? @Yanohd

**Comment by runepiper** [comment]
@FarukErtuerk We enabled tests again, see: https://github.com/visuellverstehen/markdown-to-html/actions/runs/1886267556

**Comment by FarukErtuerk** [comment]
I'm fine with it, maybe we should update the failing tests

**Comment by runepiper** [comment]
I am not sure how to extend the testing matrix and add Laravel 9. Any ideas?

**Review by runepiper — APPROVED** [review]

**Review by FarukErtuerk — APPROVED** [review]

**Pull request merged**
